spring:
  config:
    import: vault://
  cloud:
    vault:
      uri: http://198.19.227.58  # Vault 서버 주소
      authentication: token
      token: ${VAULT_SECRET}
      kv:
        enabled: true
        backend: secret
        default-context: mysql
  datasource:
    url: ${vault.datasource.url}
    username: ${vault.datasource.username}
    password: ${vault.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: project-service

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://198.19.198.98:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


#logging:
#  level:
#    org.springframework.cloud.vault: DEBUG
#    org.springframework.boot: DEBUG
#    com.zaxxer.hikari: DEBUG