apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-service
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-service
  template:
    metadata:
      labels:
        app: project-service
    spec:
      containers:
        - name: project-service
          image: sangwookie/sidekick-project-service:latest
          ports:
            - containerPort: 80
